import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Button from "./components/login-btn"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://ultra.unity.com">Ultra</a>
        </h1>
        <p>{process.env.GITHUB_CLIENT_SECRET}</p>
        <p>{process.env.NEXTAUTH_SECRET}</p>
        <p>{process.env.GITHUB_CLIENT_ID}</p>
        <p>{process.env.NEXTAUTH_URL}</p>
        <p>{process.env.GOOGLE_CLIENT_ID}</p>
        <p>{process.env.GOOGLE_CLIENT_SECRET}</p>
        <p className={styles.description}>
          <Button />
        </p>
      </main>
    </div>
  )
}
